---
title: "A cerca de nosotros"
---

Somos una fundación que formula, ejecuta e implementa planes, programas o proyectos que permitan el sostenimiento y funcionamiento de la misma. Estos serán de carácter social, prevaleciendo el desarrollo comunitario, para tal fin deberá contar con un grupo de profesionales en cada uno de los aspectos a desarrollar.


Somos una fundación que formula, ejecuta e implementar planes, programas o proyectos, que permitan el sostenimiento y funcionamiento de la misma. Estos serán de carácter social, prevaleciendo el desarrollo comunitario, para tal fin deberá contar con un grupo de profesionales en cada uno de los aspectos a desarrollar.



**Visión** 

Es una organización sin ánimo de lucro, cuyo propósito es contribuir a la generación de desarrollo territorial sostenible desde la visión económica, social, cultural, institucional y ambiental que permita mejorar las condiciones de vida de las poblaciones más vulnerables (niñez, juventud, adulto mayor, mujer, discapacitados, indígenas, negritudes, víctimas del conflicto) a través de la gestión, formulación, ejecución y evaluación de políticas públicas, planes programas y proyectos; así como la asesoría y acompañamiento a los actores que inciden en la gestión territorial.


**Misión**

Principalmente desarrollar las soluciones a las necesidades de la comunidad a través de la
comunidad misma para promover el bienestar social, ambiental, cultural y económico, a la niñez, la juventud, el adulto mayor, a la mujer, desplazados, discapacitados, indígenas, negritudes, víctimas de las minas antipersonal de las poblaciones vulnerables y desamparadas, fundamentado en el ser humano, darle condiciones para empoderarlo en la familia, la organización y por ende la sociedad. Promocionar, promover y desarrollar
programas y/o proyectos orientados a la organización, participación, liderazgo y formación personal y grupal de la población en general, posibilitando espacios y planes orientados para que las y los jóvenes, niñas y niños, discapacitados, adultos mayores, grupos étnicos, desplazados, mujeres cabeza de familia y comunidad en general, sean sujetos, protagonistas de si mismos, con capacidad de proposición y acción, a nivel de, empleo, nutrición, bienestar social, cultural, político, económico, productivo, comunitario, deportivo, recreativo y ambiental.